# Generated by Django 5.1.1 on 2024-09-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Img',
            new_name='ProImg',
        ),
    ]
